# Generated by Django 4.0.2 on 2023-02-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0002_inputvdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvdetail',
            name='PlateNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
