# Generated by Django 4.0.2 on 2023-02-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0003_alter_inputvdetail_platenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
