# Generated by Django 4.0.2 on 2023-03-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputVSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChassisNumber', models.CharField(max_length=100, unique=True)),
                ('ACUCompany', models.CharField(max_length=300)),
                ('WheelerType', models.CharField(max_length=300)),
                ('Engine', models.CharField(max_length=200)),
            ],
        ),
    ]
