# Generated by Django 4.0.2 on 2023-03-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0006_inputddetail_inputmaintenanceschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputddetail',
            old_name='DriversMedicalCondtition',
            new_name='DriversMedicalCondition',
        ),
    ]
