# Generated by Django 4.0.2 on 2023-03-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0007_rename_driversmedicalcondtition_inputddetail_driversmedicalcondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputMaintenanceSchedule',
            new_name='InputMSched',
        ),
    ]
