# Generated by Django 4.0.2 on 2023-03-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0008_rename_inputmaintenanceschedule_inputmsched'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputvspecs',
            name='VehicleImage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
