# Generated by Django 4.1.7 on 2023-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FMSApp", "0010_alter_inputvspecs_vehicleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputvspecs",
            name="VehicleImage",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
