# Generated by Django 4.1.7 on 2023-04-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FMSApp", "0011_alter_inputvspecs_vehicleimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputDeploymentSched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
