# Generated by Django 4.1.7 on 2023-04-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FMSApp", "0012_inputdeploymentsched"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inputdeploymentsched",
            old_name="date",
            new_name="Date",
        ),
        migrations.RenameField(
            model_name="inputdeploymentsched",
            old_name="location",
            new_name="DeploymentLocation",
        ),
    ]
