# Generated by Django 4.1.7 on 2023-04-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FMSApp", "0013_rename_date_inputdeploymentsched_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputmsched",
            name="TypeofRepairandMaintenance",
            field=models.CharField(max_length=300),
        ),
    ]
