# Generated by Django 4.1.7 on 2023-05-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FMSApp", "0016_alter_inputvspecs_platenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputddetail",
            name="PlateNumber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FMSApp.inputvdetail",
            ),
        ),
        migrations.AlterField(
            model_name="inputdeploymentsched",
            name="PlateNumber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FMSApp.inputvdetail",
            ),
        ),
        migrations.AlterField(
            model_name="inputmsched",
            name="PlateNumber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FMSApp.inputvdetail",
            ),
        ),
    ]
