# Generated by Django 4.1.3 on 2023-05-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0017_alter_inputddetail_platenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvspecs',
            name='PlateNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FMSApp.inputvdetail', unique=True),
        ),
    ]
