# Generated by Django 4.0.6 on 2023-05-13 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0017_alter_inputddetail_platenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('PlateNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FMSApp.inputvdetail')),
            ],
        ),
    ]
