# Generated by Django 4.0.6 on 2023-05-15 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0018_alter_inputvspecs_platenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platenumber_id', models.IntegerField()),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inputmsched',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inputmsched',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inputmsched',
            name='TypeofRepairandMaintenance',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inputvspecs',
            name='PlateNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FMSApp.inputvdetail'),
        ),
    ]
