# Generated by Django 4.0.6 on 2023-05-14 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0018_dateupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateupdated',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
