# Generated by Django 4.0.6 on 2023-05-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0019_alter_dateupdated_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateupdated',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
