# Generated by Django 4.0.6 on 2023-05-14 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0019_alter_inputvspecs_platenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvspecs',
            name='PlateNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FMSApp.inputvdetail'),
        ),
    ]
