# Generated by Django 4.0.6 on 2023-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSApp', '0020_alter_inputvspecs_platenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platenumber_id', models.IntegerField()),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
